include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
  errors:
    invalid_annotation_target: ignore
  plugins:
    - custom_lint
linter:
  rules:
formatter:
  page_width: 120
targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          preamble: |
            // coverage:ignore-file

