openapi: 3.0.1
info:
  title: Chattrix API
  description: |
    API toàn diện cho ứng dụng Chattrix, bao gồm xác thực, quản lý người dùng, và tính năng gọi điện thời gian thực.

    ---

    ### Luồng Hoạt Động của Client (Call Feature)

    Dưới đây là các bước gợi ý cho client để tích hợp tính năng gọi điện.

    #### Bước 0: Chuẩn bị
    1.  **Xác thực:** Client đăng nhập qua `POST /v1/auth/login` và nhận được một JSON Web Token (JWT).
    2.  **Kết nối WebSocket:** Client sử dụng JWT để xác thực và thiết lập một kết nối WebSocket tới endpoint của server (ví dụ: `/ws/chat`).
    3.  **Lắng nghe sự kiện:** Client phải luôn lắng nghe các tin nhắn đến trên kênh WebSocket để xử lý các sự kiện theo thời gian thực.

    ---

    #### Luồng 1: Người Gọi (Caller)
    1.  **Bắt đầu cuộc gọi:** Client gửi yêu cầu `POST /v1/calls/initiate`.
    2.  **Xử lý phản hồi:** Nếu thành công, client nhận được `CallConnectionResponse` chứa `callInfo` và `token`. Client dùng thông tin này để tham gia kênh gọi.
    3.  **Chờ phản hồi từ Người Nhận (qua WebSocket):**
        *   `call.accepted`: Cuộc gọi được chấp nhận.
        *   `call.rejected`: Cuộc gọi bị từ chối.
        *   `call.timeout`: Hết thời gian chờ.

    ---

    #### Luồng 2: Người Nhận (Callee)
    1.  **Nhận cuộc gọi đến:** Client nhận sự kiện WebSocket `call.incoming`.
    2.  **Hiển thị giao diện:** Hiển thị thông tin người gọi và nút "Chấp nhận" / "Từ chối".
    3.  **Xử lý hành động:**
        *   **Chấp nhận:** Gửi `POST /v1/calls/{callId}/accept`, nhận `token` và tham gia kênh gọi.
        *   **Từ chối:** Gửi `POST /v1/calls/{callId}/reject`.

    ---

    #### Luồng 3: Kết thúc cuộc gọi
    *   **Người kết thúc:** Gửi `POST /v1/calls/{callId}/end` và rời kênh.
    *   **Người còn lại:** Nhận sự kiện WebSocket `call.ended` và rời kênh.

    ---

    ### Chi tiết các sự kiện WebSocket
    Tất cả các tin nhắn từ server đều được bọc trong một đối tượng `WebSocketMessage` chung.
    *   **`call.incoming`**: Thông báo có cuộc gọi đến. (Payload: `CallInvitationDto`)
    *   **`call.accepted`**: Cuộc gọi đã được chấp nhận. (Payload: `CallAcceptDto`)
    *   **`call.rejected`**: Cuộc gọi đã bị từ chối. (Payload: `CallRejectDto`)
    *   **`call.ended`**: Cuộc gọi đã kết thúc. (Payload: `CallEndDto`)
    *   **`call.timeout`**: Cuộc gọi hết thời gian chờ. (Payload: `CallTimeoutDto`)
    *   **`call.quality_warning`**: Cảnh báo chất lượng kết nối. (Payload: `CallQualityWarningDto`)
  version: "1.0.0"
servers:
  - url: /api
    description: Server API chính

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    # --- Auth & User Schemas ---
    LoginRequest:
      type: object
      required: [usernameOrEmail, password]
      properties:
        usernameOrEmail: { type: string, description: "Tên đăng nhập hoặc email của người dùng." }
        password: { type: string, format: password, description: "Mật khẩu." }
    
    AuthResponse:
      type: object
      properties:
        accessToken: { type: string, description: "Token truy cập chính." }
        refreshToken: { type: string, description: "Token dùng để làm mới access token." }
        tokenType: { type: string, example: "Bearer" }
        expiresIn: { type: integer, format: int64, description: "Thời gian hết hạn của access token (tính bằng giây)." }

    UserResponse:
      type: object
      properties:
        id: { type: integer, format: int64 }
        username: { type: string }
        email: { type: string, format: email }
        fullName: { type: string }
        avatarUrl: { type: string, format: uri, nullable: true }
        isOnline: { type: boolean }
        lastSeen: { type: string, format: date-time, nullable: true }

    # --- Call Schemas ---
    CallResponse:
      type: object
      properties:
        id: { type: string, format: uuid }
        channelId: { type: string }
        status: { type: string, enum: [RINGING, CONNECTING, CONNECTED, REJECTED, ENDED, INITIATING] }
        callType: { type: string, enum: [AUDIO, VIDEO] }
        callerId: { type: integer, format: int64 }
        callerName: { type: string }
        callerAvatar: { type: string, format: uri, nullable: true }
        calleeId: { type: integer, format: int64 }
        calleeName: { type: string }
        calleeAvatar: { type: string, format: uri, nullable: true }
        createdAt: { type: string, format: date-time }
        durationSeconds: { type: integer, nullable: true }

    CallConnectionResponse:
      type: object
      properties:
        callInfo: { $ref: '#/components/schemas/CallResponse' }
        token: { type: string, description: "Token (ví dụ: Agora Token) để kết nối vào phiên gọi." }

    # --- Generic API Response Wrappers ---
    ApiResponse_AuthResponse:
      type: object
      properties:
        success: { type: boolean, example: true }
        message: { type: string }
        data: { $ref: '#/components/schemas/AuthResponse' }

    ApiResponse_UserResponse:
      type: object
      properties:
        success: { type: boolean, example: true }
        message: { type: string }
        data: { $ref: '#/components/schemas/UserResponse' }
    
    ApiResponse_UserListResponse:
      type: object
      properties:
        success: { type: boolean, example: true }
        message: { type: string }
        data:
          type: array
          items:
            $ref: '#/components/schemas/UserResponse'

    ApiResponse_CallConnectionResponse:
      type: object
      properties:
        success: { type: boolean, example: true }
        message: { type: string }
        data: { $ref: '#/components/schemas/CallConnectionResponse' }

    ApiResponse_CallResponse:
      type: object
      properties:
        success: { type: boolean, example: true }
        message: { type: string }
        data: { $ref: '#/components/schemas/CallResponse' }

    # --- Request Schemas ---
    InitiateCallRequest:
      type: object
      required: [calleeId, callType]
      properties:
        calleeId: { type: integer, format: int64 }
        callType: { type: string, enum: [AUDIO, VIDEO] }

    RejectCallRequest:
      type: object
      required: [reason]
      properties:
        reason: { type: string, enum: [busy, declined, unavailable] }

    EndCallRequest:
      type: object
      properties:
        reason: { type: string, enum: [hangup, "network error", "device error", timeout], default: "hangup" }

    # --- WebSocket DTOs ---
    CallInvitationDto:
      type: object
      properties:
        callId: { type: string, format: uuid }
        channelId: { type: string }
        callerId: { type: integer, format: int64 }
        callerName: { type: string }
        callerAvatar: { type: string, format: uri }
        callType: { type: string, enum: [AUDIO, VIDEO] }

    CallAcceptDto:
      type: object
      properties:
        callId: { type: string, format: uuid }
        acceptedBy: { type: integer, format: int64 }

    CallRejectDto:
      type: object
      properties:
        callId: { type: string, format: uuid }
        rejectedBy: { type: integer, format: int64 }
        reason: { type: string, enum: [busy, declined, unavailable] }

    CallEndDto:
      type: object
      properties:
        callId: { type: string, format: uuid }
        endedBy: { type: integer, format: int64 }
        durationSeconds: { type: integer }

    CallTimeoutDto:
      type: object
      properties:
        callId: { type: string, format: uuid }
        reason: { type: string, example: "no_answer" }

    CallQualityWarningDto:
      type: object
      properties:
        callId: { type: string, format: uuid }
        userId: { type: integer, format: int64 }
        message: { type: string }

security:
  - bearerAuth: []

tags:
  - name: Authentication
    description: "Các API liên quan đến xác thực, đăng nhập, đăng ký và quản lý phiên làm việc."
  - name: Users
    description: "Các API liên quan đến quản lý người dùng."
  - name: Call
    description: "Các API để quản lý tính năng gọi điện."

paths:
  # --- Auth Paths ---
  /v1/auth/login:
    post:
      summary: "User Login"
      description: "Xác thực người dùng bằng username/email và password để nhận về access token và refresh token."
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/LoginRequest' }
      responses:
        '200':
          description: "Login successful."
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ApiResponse_AuthResponse' }
        '400':
          description: "Bad Request (e.g., invalid credentials)."
        '401':
          description: "Unauthorized (e.g., account not verified)."

  /v1/auth/me:
    get:
      summary: "Get Current User Info"
      description: "Lấy thông tin chi tiết của người dùng đang đăng nhập, dựa trên token xác thực."
      tags: [Authentication]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: "User retrieved successfully."
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ApiResponse_UserResponse' }
        '401':
          description: "Unauthorized."

  # --- User Paths ---
  /v1/users:
    get:
      summary: "Get All Users"
      description: "Lấy danh sách tất cả người dùng trong hệ thống. Yêu cầu xác thực."
      tags: [Users]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: "Users retrieved successfully."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_UserListResponse'
        '401':
          description: "Unauthorized."

  # --- Call Paths ---
  /v1/calls/initiate:
    post:
      summary: "Initiate a new call"
      description: "Bắt đầu một cuộc gọi đến một người dùng khác. User ID của người gọi được lấy từ token xác thực."
      tags: [Call]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/InitiateCallRequest' }
      responses:
        '201':
          description: "Call initiated successfully."
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ApiResponse_CallConnectionResponse' }
        '400':
          description: "Bad Request."
        '401':
          description: "Unauthorized."

  /v1/calls/{callId}/accept:
    post:
      summary: "Accept a call"
      description: "Người nhận chấp nhận một cuộc gọi đến. User ID của người nhận được lấy từ token xác thực."
      tags: [Call]
      security:
        - bearerAuth: []
      parameters:
        - name: callId
          in: path
          required: true
          schema: { type: string, format: uuid }
      responses:
        '200':
          description: "Call accepted successfully."
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ApiResponse_CallConnectionResponse' }
        '401':
          description: "Unauthorized."
        '404':
          description: "Call not found."

  /v1/calls/{callId}/reject:
    post:
      summary: "Reject a call"
      description: "Người nhận từ chối một cuộc gọi đến. User ID của người nhận được lấy từ token xác thực."
      tags: [Call]
      security:
        - bearerAuth: []
      parameters:
        - name: callId
          in: path
          required: true
          schema: { type: string, format: uuid }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/RejectCallRequest' }
      responses:
        '200':
          description: "Call rejected successfully."
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ApiResponse_CallResponse' }
        '401':
          description: "Unauthorized."
        '404':
          description: "Call not found."

  /v1/calls/{callId}/end:
    post:
      summary: "End a call"
      description: "Một trong hai bên kết thúc cuộc gọi. User ID của người thực hiện hành động được lấy từ token xác thực."
      tags: [Call]
      security:
        - bearerAuth: []
      parameters:
        - name: callId
          in: path
          required: true
          schema: { type: string, format: uuid }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/EndCallRequest' }
      responses:
        '200':
          description: "Call ended successfully."
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ApiResponse_CallResponse' }
        '401':
          description: "Unauthorized."
        '404':
          description: "Call not found."
