// Mocks generated by Mockito 5.4.6 from annotations
// in chattrix_ui/test/features/call/data/services/agora_websocket_independence_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:chattrix_ui/features/chat/data/services/chat_websocket_service.dart'
    as _i2;
import 'package:chattrix_ui/features/chat/domain/entities/conversation_update.dart'
    as _i7;
import 'package:chattrix_ui/features/chat/domain/entities/message.dart' as _i4;
import 'package:chattrix_ui/features/chat/domain/entities/typing_indicator.dart'
    as _i5;
import 'package:chattrix_ui/features/chat/domain/entities/user_status_update.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ChatWebSocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatWebSocketService extends _i1.Mock
    implements _i2.ChatWebSocketService {
  MockChatWebSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.Message> get messageStream =>
      (super.noSuchMethod(
            Invocation.getter(#messageStream),
            returnValue: _i3.Stream<_i4.Message>.empty(),
          )
          as _i3.Stream<_i4.Message>);

  @override
  _i3.Stream<_i5.TypingIndicator> get typingStream =>
      (super.noSuchMethod(
            Invocation.getter(#typingStream),
            returnValue: _i3.Stream<_i5.TypingIndicator>.empty(),
          )
          as _i3.Stream<_i5.TypingIndicator>);

  @override
  _i3.Stream<_i6.UserStatusUpdate> get userStatusStream =>
      (super.noSuchMethod(
            Invocation.getter(#userStatusStream),
            returnValue: _i3.Stream<_i6.UserStatusUpdate>.empty(),
          )
          as _i3.Stream<_i6.UserStatusUpdate>);

  @override
  _i3.Stream<_i7.ConversationUpdate> get conversationUpdateStream =>
      (super.noSuchMethod(
            Invocation.getter(#conversationUpdateStream),
            returnValue: _i3.Stream<_i7.ConversationUpdate>.empty(),
          )
          as _i3.Stream<_i7.ConversationUpdate>);

  @override
  _i3.Stream<bool> get connectionStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectionStream),
            returnValue: _i3.Stream<bool>.empty(),
          )
          as _i3.Stream<bool>);

  @override
  _i3.Stream<Map<String, dynamic>> get rawMessageStream =>
      (super.noSuchMethod(
            Invocation.getter(#rawMessageStream),
            returnValue: _i3.Stream<Map<String, dynamic>>.empty(),
          )
          as _i3.Stream<Map<String, dynamic>>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i3.Future<void> connect(String? accessToken) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [accessToken]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void sendMessage(
    String? conversationId,
    String? content, {
    int? replyToMessageId,
  }) => super.noSuchMethod(
    Invocation.method(
      #sendMessage,
      [conversationId, content],
      {#replyToMessageId: replyToMessageId},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void sendTypingStart(String? conversationId) => super.noSuchMethod(
    Invocation.method(#sendTypingStart, [conversationId]),
    returnValueForMissingStub: null,
  );

  @override
  void sendTypingStop(String? conversationId) => super.noSuchMethod(
    Invocation.method(#sendTypingStop, [conversationId]),
    returnValueForMissingStub: null,
  );

  @override
  void sendHeartbeat() => super.noSuchMethod(
    Invocation.method(#sendHeartbeat, []),
    returnValueForMissingStub: null,
  );

  @override
  void sendGenericMessage(Map<String, dynamic>? payload) => super.noSuchMethod(
    Invocation.method(#sendGenericMessage, [payload]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
