// Mocks generated by Mockito 5.4.6 from annotations
// in chattrix_ui/test/features/call/data/repositories/call_websocket_reconnection_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:chattrix_ui/core/errors/failures.dart' as _i10;
import 'package:chattrix_ui/features/call/data/datasources/call_local_datasource_impl.dart'
    as _i7;
import 'package:chattrix_ui/features/call/data/datasources/call_remote_datasource.dart'
    as _i9;
import 'package:chattrix_ui/features/call/data/models/call_model.dart' as _i12;
import 'package:chattrix_ui/features/call/data/models/websocket/call_accepted_data.dart'
    as _i17;
import 'package:chattrix_ui/features/call/data/models/websocket/call_ended_data.dart'
    as _i20;
import 'package:chattrix_ui/features/call/data/models/websocket/call_invitation_data.dart'
    as _i16;
import 'package:chattrix_ui/features/call/data/models/websocket/call_quality_warning_data.dart'
    as _i21;
import 'package:chattrix_ui/features/call/data/models/websocket/call_rejected_data.dart'
    as _i18;
import 'package:chattrix_ui/features/call/data/models/websocket/call_timeout_data.dart'
    as _i19;
import 'package:chattrix_ui/features/call/data/services/agora_service.dart'
    as _i5;
import 'package:chattrix_ui/features/call/data/services/call_signaling_service.dart'
    as _i15;
import 'package:chattrix_ui/features/call/data/services/permission_service.dart'
    as _i14;
import 'package:chattrix_ui/features/call/data/services/token_service.dart'
    as _i13;
import 'package:chattrix_ui/features/call/domain/entities/call_entity.dart'
    as _i11;
import 'package:chattrix_ui/features/call/domain/entities/call_history_entity.dart'
    as _i8;
import 'package:chattrix_ui/features/chat/data/services/chat_websocket_service.dart'
    as _i22;
import 'package:chattrix_ui/features/chat/domain/entities/conversation_update.dart'
    as _i26;
import 'package:chattrix_ui/features/chat/domain/entities/message.dart' as _i23;
import 'package:chattrix_ui/features/chat/domain/entities/typing_indicator.dart'
    as _i24;
import 'package:chattrix_ui/features/chat/domain/entities/user_status_update.dart'
    as _i25;
import 'package:dartz/dartz.dart' as _i4;
import 'package:dio/dio.dart' as _i3;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFlutterSecureStorage_0 extends _i1.SmartFake
    implements _i2.FlutterSecureStorage {
  _FakeFlutterSecureStorage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_1 extends _i1.SmartFake implements _i3.Dio {
  _FakeDio_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AgoraService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgoraService extends _i1.Mock implements _i5.AgoraService {
  MockAgoraService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i5.CallEvent> get events =>
      (super.noSuchMethod(
            Invocation.getter(#events),
            returnValue: _i6.Stream<_i5.CallEvent>.empty(),
          )
          as _i6.Stream<_i5.CallEvent>);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isInChannel =>
      (super.noSuchMethod(Invocation.getter(#isInChannel), returnValue: false)
          as bool);

  @override
  _i6.Future<void> initialize(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [appId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> joinChannel({
    required String? token,
    required String? channelId,
    required int? uid,
    required bool? isVideo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#joinChannel, [], {
              #token: token,
              #channelId: channelId,
              #uid: uid,
              #isVideo: isVideo,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> leaveChannel() =>
      (super.noSuchMethod(
            Invocation.method(#leaveChannel, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> muteLocalAudioStream(bool? mute) =>
      (super.noSuchMethod(
            Invocation.method(#muteLocalAudioStream, [mute]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> muteLocalVideoStream(bool? mute) =>
      (super.noSuchMethod(
            Invocation.method(#muteLocalVideoStream, [mute]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> switchCamera() =>
      (super.noSuchMethod(
            Invocation.method(#switchCamera, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> enableVideo() =>
      (super.noSuchMethod(
            Invocation.method(#enableVideo, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> enableAudio() =>
      (super.noSuchMethod(
            Invocation.method(#enableAudio, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [CallLocalDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallLocalDataSourceImpl extends _i1.Mock
    implements _i7.CallLocalDataSourceImpl {
  MockCallLocalDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FlutterSecureStorage get secureStorage =>
      (super.noSuchMethod(
            Invocation.getter(#secureStorage),
            returnValue: _FakeFlutterSecureStorage_0(
              this,
              Invocation.getter(#secureStorage),
            ),
          )
          as _i2.FlutterSecureStorage);

  @override
  _i6.Future<void> saveCallHistory(_i8.CallHistoryEntity? callHistory) =>
      (super.noSuchMethod(
            Invocation.method(#saveCallHistory, [callHistory]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.CallHistoryEntity>> getCallHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getCallHistory, []),
            returnValue: _i6.Future<List<_i8.CallHistoryEntity>>.value(
              <_i8.CallHistoryEntity>[],
            ),
          )
          as _i6.Future<List<_i8.CallHistoryEntity>>);

  @override
  _i6.Future<void> deleteCallHistory(String? callId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCallHistory, [callId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearCallHistory() =>
      (super.noSuchMethod(
            Invocation.method(#clearCallHistory, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [CallRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallRemoteDataSource extends _i1.Mock
    implements _i9.CallRemoteDataSource {
  MockCallRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_1(this, Invocation.getter(#dio)),
          )
          as _i3.Dio);

  @override
  _i6.Future<_i4.Either<_i10.Failure, Map<String, dynamic>>> initiateCall({
    required String? calleeId,
    required _i11.CallType? callType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initiateCall, [], {
              #calleeId: calleeId,
              #callType: callType,
            }),
            returnValue:
                _i6.Future<
                  _i4.Either<_i10.Failure, Map<String, dynamic>>
                >.value(
                  _FakeEither_2<_i10.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#initiateCall, [], {
                      #calleeId: calleeId,
                      #callType: callType,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i10.Failure, Map<String, dynamic>>>);

  @override
  _i6.Future<_i4.Either<_i10.Failure, _i12.CallModel>> acceptCall(
    String? callId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#acceptCall, [callId]),
            returnValue:
                _i6.Future<_i4.Either<_i10.Failure, _i12.CallModel>>.value(
                  _FakeEither_2<_i10.Failure, _i12.CallModel>(
                    this,
                    Invocation.method(#acceptCall, [callId]),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i10.Failure, _i12.CallModel>>);

  @override
  _i6.Future<_i4.Either<_i10.Failure, void>> rejectCall(
    String? callId,
    String? reason,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#rejectCall, [callId, reason]),
            returnValue: _i6.Future<_i4.Either<_i10.Failure, void>>.value(
              _FakeEither_2<_i10.Failure, void>(
                this,
                Invocation.method(#rejectCall, [callId, reason]),
              ),
            ),
          )
          as _i6.Future<_i4.Either<_i10.Failure, void>>);

  @override
  _i6.Future<_i4.Either<_i10.Failure, void>> endCall(
    String? callId,
    int? durationSeconds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#endCall, [callId, durationSeconds]),
            returnValue: _i6.Future<_i4.Either<_i10.Failure, void>>.value(
              _FakeEither_2<_i10.Failure, void>(
                this,
                Invocation.method(#endCall, [callId, durationSeconds]),
              ),
            ),
          )
          as _i6.Future<_i4.Either<_i10.Failure, void>>);
}

/// A class which mocks [TokenService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenService extends _i1.Mock implements _i13.TokenService {
  MockTokenService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Either<_i10.Failure, Map<String, dynamic>>> fetchToken({
    required String? channelId,
    String? role = 'publisher',
    int? expirationSeconds = 3600,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchToken, [], {
              #channelId: channelId,
              #role: role,
              #expirationSeconds: expirationSeconds,
            }),
            returnValue:
                _i6.Future<
                  _i4.Either<_i10.Failure, Map<String, dynamic>>
                >.value(
                  _FakeEither_2<_i10.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#fetchToken, [], {
                      #channelId: channelId,
                      #role: role,
                      #expirationSeconds: expirationSeconds,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i10.Failure, Map<String, dynamic>>>);

  @override
  _i6.Future<_i4.Either<_i10.Failure, Map<String, dynamic>>> refreshToken({
    required String? channelId,
    required String? oldToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, [], {
              #channelId: channelId,
              #oldToken: oldToken,
            }),
            returnValue:
                _i6.Future<
                  _i4.Either<_i10.Failure, Map<String, dynamic>>
                >.value(
                  _FakeEither_2<_i10.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#refreshToken, [], {
                      #channelId: channelId,
                      #oldToken: oldToken,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i10.Failure, Map<String, dynamic>>>);

  @override
  _i6.Future<_i4.Either<_i10.Failure, Map<String, dynamic>>>
  handleTokenExpiration({
    required String? channelId,
    required String? oldToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#handleTokenExpiration, [], {
              #channelId: channelId,
              #oldToken: oldToken,
            }),
            returnValue:
                _i6.Future<
                  _i4.Either<_i10.Failure, Map<String, dynamic>>
                >.value(
                  _FakeEither_2<_i10.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#handleTokenExpiration, [], {
                      #channelId: channelId,
                      #oldToken: oldToken,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i10.Failure, Map<String, dynamic>>>);
}

/// A class which mocks [PermissionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionService extends _i1.Mock implements _i14.PermissionService {
  MockPermissionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Either<_i10.Failure, bool>> requestCameraPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestCameraPermission, []),
            returnValue: _i6.Future<_i4.Either<_i10.Failure, bool>>.value(
              _FakeEither_2<_i10.Failure, bool>(
                this,
                Invocation.method(#requestCameraPermission, []),
              ),
            ),
          )
          as _i6.Future<_i4.Either<_i10.Failure, bool>>);

  @override
  _i6.Future<_i4.Either<_i10.Failure, bool>> requestMicrophonePermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestMicrophonePermission, []),
            returnValue: _i6.Future<_i4.Either<_i10.Failure, bool>>.value(
              _FakeEither_2<_i10.Failure, bool>(
                this,
                Invocation.method(#requestMicrophonePermission, []),
              ),
            ),
          )
          as _i6.Future<_i4.Either<_i10.Failure, bool>>);

  @override
  _i6.Future<bool> checkCameraPermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkCameraPermission, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> checkMicrophonePermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkMicrophonePermission, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> openAppSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openAppSettings, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [CallSignalingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallSignalingService extends _i1.Mock
    implements _i15.CallSignalingService {
  MockCallSignalingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i16.CallInvitationData> get callInvitationStream =>
      (super.noSuchMethod(
            Invocation.getter(#callInvitationStream),
            returnValue: _i6.Stream<_i16.CallInvitationData>.empty(),
          )
          as _i6.Stream<_i16.CallInvitationData>);

  @override
  _i6.Stream<_i17.CallAcceptedData> get callAcceptedStream =>
      (super.noSuchMethod(
            Invocation.getter(#callAcceptedStream),
            returnValue: _i6.Stream<_i17.CallAcceptedData>.empty(),
          )
          as _i6.Stream<_i17.CallAcceptedData>);

  @override
  _i6.Stream<_i18.CallRejectedData> get callRejectedStream =>
      (super.noSuchMethod(
            Invocation.getter(#callRejectedStream),
            returnValue: _i6.Stream<_i18.CallRejectedData>.empty(),
          )
          as _i6.Stream<_i18.CallRejectedData>);

  @override
  _i6.Stream<_i19.CallTimeoutData> get callTimeoutStream =>
      (super.noSuchMethod(
            Invocation.getter(#callTimeoutStream),
            returnValue: _i6.Stream<_i19.CallTimeoutData>.empty(),
          )
          as _i6.Stream<_i19.CallTimeoutData>);

  @override
  _i6.Stream<_i20.CallEndedData> get callEndedStream =>
      (super.noSuchMethod(
            Invocation.getter(#callEndedStream),
            returnValue: _i6.Stream<_i20.CallEndedData>.empty(),
          )
          as _i6.Stream<_i20.CallEndedData>);

  @override
  _i6.Stream<_i21.CallQualityWarningData> get callQualityWarningStream =>
      (super.noSuchMethod(
            Invocation.getter(#callQualityWarningStream),
            returnValue: _i6.Stream<_i21.CallQualityWarningData>.empty(),
          )
          as _i6.Stream<_i21.CallQualityWarningData>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i4.Either<_i10.Failure, void> sendCallInvitation({
    required String? callId,
    required String? channelId,
    required String? callerId,
    required String? callerName,
    required String? recipientId,
    required _i11.CallType? callType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendCallInvitation, [], {
              #callId: callId,
              #channelId: channelId,
              #callerId: callerId,
              #callerName: callerName,
              #recipientId: recipientId,
              #callType: callType,
            }),
            returnValue: _FakeEither_2<_i10.Failure, void>(
              this,
              Invocation.method(#sendCallInvitation, [], {
                #callId: callId,
                #channelId: channelId,
                #callerId: callerId,
                #callerName: callerName,
                #recipientId: recipientId,
                #callType: callType,
              }),
            ),
          )
          as _i4.Either<_i10.Failure, void>);

  @override
  _i4.Either<_i10.Failure, void> sendCallAccept({required String? callId}) =>
      (super.noSuchMethod(
            Invocation.method(#sendCallAccept, [], {#callId: callId}),
            returnValue: _FakeEither_2<_i10.Failure, void>(
              this,
              Invocation.method(#sendCallAccept, [], {#callId: callId}),
            ),
          )
          as _i4.Either<_i10.Failure, void>);

  @override
  _i4.Either<_i10.Failure, void> sendCallReject({
    required String? callId,
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendCallReject, [], {
              #callId: callId,
              #reason: reason,
            }),
            returnValue: _FakeEither_2<_i10.Failure, void>(
              this,
              Invocation.method(#sendCallReject, [], {
                #callId: callId,
                #reason: reason,
              }),
            ),
          )
          as _i4.Either<_i10.Failure, void>);

  @override
  _i4.Either<_i10.Failure, void> sendCallEnded({
    required String? callId,
    int? durationSeconds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendCallEnded, [], {
              #callId: callId,
              #durationSeconds: durationSeconds,
            }),
            returnValue: _FakeEither_2<_i10.Failure, void>(
              this,
              Invocation.method(#sendCallEnded, [], {
                #callId: callId,
                #durationSeconds: durationSeconds,
              }),
            ),
          )
          as _i4.Either<_i10.Failure, void>);

  @override
  void handleIncomingMessage(Map<String, dynamic>? data) => super.noSuchMethod(
    Invocation.method(#handleIncomingMessage, [data]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ChatWebSocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatWebSocketService extends _i1.Mock
    implements _i22.ChatWebSocketService {
  MockChatWebSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i23.Message> get messageStream =>
      (super.noSuchMethod(
            Invocation.getter(#messageStream),
            returnValue: _i6.Stream<_i23.Message>.empty(),
          )
          as _i6.Stream<_i23.Message>);

  @override
  _i6.Stream<_i24.TypingIndicator> get typingStream =>
      (super.noSuchMethod(
            Invocation.getter(#typingStream),
            returnValue: _i6.Stream<_i24.TypingIndicator>.empty(),
          )
          as _i6.Stream<_i24.TypingIndicator>);

  @override
  _i6.Stream<_i25.UserStatusUpdate> get userStatusStream =>
      (super.noSuchMethod(
            Invocation.getter(#userStatusStream),
            returnValue: _i6.Stream<_i25.UserStatusUpdate>.empty(),
          )
          as _i6.Stream<_i25.UserStatusUpdate>);

  @override
  _i6.Stream<_i26.ConversationUpdate> get conversationUpdateStream =>
      (super.noSuchMethod(
            Invocation.getter(#conversationUpdateStream),
            returnValue: _i6.Stream<_i26.ConversationUpdate>.empty(),
          )
          as _i6.Stream<_i26.ConversationUpdate>);

  @override
  _i6.Stream<bool> get connectionStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectionStream),
            returnValue: _i6.Stream<bool>.empty(),
          )
          as _i6.Stream<bool>);

  @override
  _i6.Stream<Map<String, dynamic>> get rawMessageStream =>
      (super.noSuchMethod(
            Invocation.getter(#rawMessageStream),
            returnValue: _i6.Stream<Map<String, dynamic>>.empty(),
          )
          as _i6.Stream<Map<String, dynamic>>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i6.Future<void> connect(String? accessToken) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [accessToken]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void sendMessage(
    String? conversationId,
    String? content, {
    int? replyToMessageId,
  }) => super.noSuchMethod(
    Invocation.method(
      #sendMessage,
      [conversationId, content],
      {#replyToMessageId: replyToMessageId},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void sendTypingStart(String? conversationId) => super.noSuchMethod(
    Invocation.method(#sendTypingStart, [conversationId]),
    returnValueForMissingStub: null,
  );

  @override
  void sendTypingStop(String? conversationId) => super.noSuchMethod(
    Invocation.method(#sendTypingStop, [conversationId]),
    returnValueForMissingStub: null,
  );

  @override
  void sendHeartbeat() => super.noSuchMethod(
    Invocation.method(#sendHeartbeat, []),
    returnValueForMissingStub: null,
  );

  @override
  void sendGenericMessage(Map<String, dynamic>? payload) => super.noSuchMethod(
    Invocation.method(#sendGenericMessage, [payload]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
